Get camera by cameraID
PurdueCAM2Project/CameraDatabaseClient pull request #19
Opened 2018-06-22 18:01 UTC by JiaEnChua

2018-06-27 18:33 UTC, mush-zhang requested changes

2018-06-27 18:33 UTC, mush-zhang commented on pythonAPIClient/client.py
> +    def _check_token(self, response, flag, url=base_URL, data=None, params=None):
to sync with master, remove the default value of url

2018-06-27 18:36 UTC, mush-zhang commented
there is linting error that prevent it from passing circleci. also, could you merge master onto the branch? thank you!

2018-06-27 18:37 UTC, mush-zhang commented on pythonAPIClient/client.py
> +    def _check_token(self, response, flag, url=base_URL, data=None, params=None):
merging master onto the branch and resolve confilcts would solve the problem

2018-06-28 14:20 UTC, mush-zhang approved these changes

2018-06-28 14:21 UTC, mush-zhang requested changes

2018-06-28 14:21 UTC, mush-zhang commented on pythonAPIClient/client.py
> +        return response.json()
we should return a camera object instead

2018-06-29 20:16 UTC, mush-zhang approved these changes

2018-07-03 18:12 UTC, Sripathm2 approved these changes
grt job

2018-07-03 19:57 UTC, Mrjimjr approved these changes
Looks good. Your Test function names are descriptive. I don't think any docstrings are needed.

2018-07-04 15:16 UTC, merged