Get token code
PurdueCAM2Project/CameraDatabaseClient pull request #2
Opened 2018-04-07 01:32 UTC by sripathm22

2018-04-07 17:19 UTC, samyellin commented on pythonAPIClient/client.py
> +#from .error import Error
Should we just wait to merge this until those classes are complete?

2018-04-07 17:20 UTC, samyellin commented on pythonAPIClient/client.py
> +    Client = Client(clinetID,clientSecret)
I don't think we should have this section in master. This type of code is for testing

2018-04-07 17:22 UTC, samyellin commented on pythonAPIClient/client.py
> +        return response.json()['token']
This function should probably check for the response and throw an error if there's some problem

2018-04-07 23:26 UTC, mush-zhang commented on pythonAPIClient/client.py
> +#from .error import Error
are those import statements giving errors?

2018-04-07 23:27 UTC, mush-zhang commented on pythonAPIClient/client.py
> +        return response.json()['token']
second.
you can check the status code with requests

2018-04-09 12:14 UTC, sripathm22 commented on pythonAPIClient/client.py
> +#from .error import Error
yes they are giving errors

2018-04-09 21:01 UTC, mush-zhang requested changes
let's add testcases for now

2018-04-12 19:26 UTC, mush-zhang approved these changes

2018-04-12 19:55 UTC, merged