test cases for reset_secret
PurdueCAM2Project/CameraDatabaseClient pull request #22
Opened 2018-07-05 20:43 UTC by shreeyan08

Please review "method reset_secret" and "testcases for reset_secret method"

2018-07-05 20:52 UTC, mush-zhang requested changes

2018-07-05 20:52 UTC, mush-zhang commented on pythonAPIClient/client.py
> +        cliendID: str
*clientID* typo

2018-07-12 16:07 UTC, jaydenC88 approved these changes
Good work!

2018-07-12 16:13 UTC, moealani approved these changes
Nice work just need to fix the typos

2018-07-12 18:04 UTC, Mrjimjr approved these changes
Good Work

2018-07-13 17:22 UTC, mush-zhang approved these changes

2018-07-13 18:01 UTC, mush-zhang commented
Shreeyan created a feature branch of the identical change. we shall close this pr generated from fork.

2018-07-13 18:01 UTC, closed without merging