implemented **Kwargs in add_camera + some lint error fixes
PurdueCAM2Project/CameraDatabaseClient pull request #27
Opened 2018-07-16 06:12 UTC by moealani

2018-07-16 06:19 UTC, moealani commented
Not sure how to fix the error I am getting on CircleCI. I assume it is an easy fix though.

2018-07-16 13:27 UTC, mush-zhang requested changes

2018-07-16 13:27 UTC, mush-zhang commented on pythonAPIClient/client.py
> +                    'video_path': kwargs.pop('video_path')
you cannot guarantee that these keys exists. if user does not provide model, then dict.pop('model') will raise a key error. specifying default value when no key found. like `'model': kwargs.pop('model', None);`

2018-07-16 13:54 UTC, mush-zhang requested changes

2018-07-16 13:54 UTC, mush-zhang commented on pythonAPIClient/client.py
> +                         'snapshot_url', 'm3u8_url', 'ip')
ip, snapshot_url, m3u8_url, and ip should not be required

2018-07-16 16:30 UTC, mush-zhang requested changes

2018-07-16 16:30 UTC, mush-zhang commented on pythonAPIClient/client.py
> +                    'snapshot_url': kwargs.pop('snapshot_url', None)
we can simplify retrieval of by `kwargs['retrieval'] = { 'snapshot_url' : kwargs.pop('snapshot_url', None)` without first checking if it is there. if the any of the fields are not specified, they will be None and error will be returned by the api.
same for ip and stream camera.

2018-07-17 01:02 UTC, jaydenC88 approved these changes
Good job

2018-07-17 13:56 UTC, mush-zhang approved these changes

2018-07-17 13:56 UTC, merged