**Kwargs in update_camera()
PurdueCAM2Project/CameraDatabaseClient pull request #28
Opened 2018-07-16 14:51 UTC by moealani

2018-07-16 19:58 UTC, mush-zhang requested changes

2018-07-16 19:58 UTC, mush-zhang commented on pythonAPIClient/client.py
> +        elif kwargs.get('type') == 'non-ip':
`non_ip`

2018-07-17 01:03 UTC, jaydenC88 approved these changes
Good work

2018-07-17 13:57 UTC, mush-zhang approved these changes

2018-07-17 16:27 UTC, merged