Documented example for each method
PurdueCAM2Project/CameraDatabaseClient pull request #39
Opened 2018-08-27 18:17 UTC by JiaEnChua

2018-08-27 19:35 UTC, moealani reviewed
Do you think using dashes instead of underscores is better so we can be consistent with the rest of the documentation? Other than that great job 👍

2018-08-29 02:37 UTC, JiaEnChua commented
@moealani you are right, I didn't notice the difference, thanks

2018-09-05 22:27 UTC, mush-zhang requested changes
I have left one comment on the update_owner method. This would apply to other methods, especially those methods that are only accessible with webUI permission.

2018-09-05 22:27 UTC, mush-zhang commented on CAM2CameraDatabaseAPIClient/client.py
> +            client.update_owner(self.clientID, 'testowner')
usually this method will be used to: `webUI_client.update_owner(userClientID, 'userClientOwner')` We might want to add more descriptive explanation and use-case scenario.

2018-09-19 16:15 UTC, mush-zhang approved these changes

2018-09-27 23:19 UTC, Sripathm2 approved these changes

2018-09-27 23:20 UTC, Mrjimjr approved these changes

2018-09-27 23:20 UTC, merged