updated search route documentation.
PurdueCAM2Project/CameraDatabaseClient pull request #41
Opened 2018-09-01 15:03 UTC by sripathm22

2018-09-05 22:22 UTC, mush-zhang requested changes

2018-09-05 22:22 UTC, mush-zhang commented on CAM2CameraDatabaseAPIClient/client.py
> +                search_camera(**kwargs)
you should first create a client say `a_client = Client('id', 'pass')` and `a_client.search_camera(**kwargs)`. Also, `a_client.search_camera(camera_type='ip', city='West Lafayette')` would also work.

2018-09-05 22:22 UTC, mush-zhang commented on CAM2CameraDatabaseAPIClient/client.py
> +                kwargs = {'camera_type': 'ip', 'city': 'West Lafayette'}
will this line show in the documentation "code-like"?

2018-09-08 16:15 UTC, sripathm22 commented on CAM2CameraDatabaseAPIClient/client.py
> +                kwargs = {'camera_type': 'ip', 'city': 'West Lafayette'}
yes i think so.

2018-09-08 16:15 UTC, sripathm22 commented on CAM2CameraDatabaseAPIClient/client.py
> +                search_camera(**kwargs)
done

2018-09-20 17:13 UTC, jaydenC88 approved these changes
Good job

2018-09-21 01:18 UTC, mush-zhang commented on CAM2CameraDatabaseAPIClient/client.py
> +                kwargs = {'camera_type': 'ip', 'city': 'West Lafayette'}
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2018-09-22 18:08 UTC, sripathm22 commented on CAM2CameraDatabaseAPIClient/client.py
> +                kwargs = {'camera_type': 'ip', 'city': 'West Lafayette'}
@mush-zhang  yes it will i just double checked it with the link and the document that we have.

2018-09-26 20:55 UTC, mush-zhang approved these changes
Great!

2018-09-26 23:27 UTC, merged